<?php

/** 
 * [BEGIN_COT_EXT]
 * Hooks=page.main
 * [END_COT_EXT]
 */
 
/**
 * plugin Page Alias Tpl for Cotonti Siena
 * 
 * @package pagealtpl
 * @version 1.0.0
 * @author esclkm
 * @copyright 
 * @license BSD
 *  */
// Generated by Cotonti developer tool (littledev.ru)
defined('COT_CODE') or die('Wrong URL.');

if(!empty($al) && file_exists("{$cfg['themes_dir']}/{$usr['theme']}/modules/page.al_".$al.".tpl"))
{
	$mskin = "{$cfg['themes_dir']}/{$usr['theme']}/modules/page.al_".$al.".tpl";
}

?>