<?php


/**
 * [BEGIN_COT_EXT]
 * Code=pagealtpl
 * Name=Page Alias Tpl
 * Category=misc-ext
 * Description=pagealtpl
 * Version=1.0.0
 * Date=2015-11-21
 * Author=esclkm
 * Auth_guests=R
 * Lock_guests=12345A
 * Auth_members=RW
 * Requires_modules=page
 * [END_COT_EXT]
 * 
 *  */

/**
 * plugin Page Alias Tpl for Cotonti Siena
 * 
 * @package pagealtpl
 * @version 1.0.0
 * @author esclkm
 * @copyright 
 * @license BSD
 *  */
// Generated by Cotonti developer tool (littledev.ru)
defined('COT_CODE') or die('Wrong URL');

?>