<?php

/** 
 * [BEGIN_COT_EXT]
 * Hooks=tools
 * [END_COT_EXT]
 */
 
/**
 * plugin Exfld Group Editor for Cotonti Siena
 * 
 * @package Exfld Group Editor
 * @version 1.0.0
 * @author esclkm
 * @copyright esclkm
 * @license BSD
 *  */
// Generated by Cotonti developer tool (littledev.ru)
defined('COT_CODE') or die('Wrong URL.');

require_once cot_langfile('exfldgroupeditor', 'plug');
require_once cot_incfile('exfldgroupeditor', 'plug');
require_once cot_incfile('pageplus', 'plug');

require_once cot_incfile('page', 'module');
require_once cot_incfile('forms');

$c = cot_import('c', 'G', 'TXT');

$rfield = cot_import('rfield', 'P', 'ARR');
$rdesc = cot_import('rdesc', 'P', 'ARR');
$rnum = cot_import('rnum', 'P', 'ARR');
$rid = cot_import('rid', 'P', 'ARR');
$rtype = cot_import('rtype', 'P', 'ARR');
$rfilter = cot_import('rfilter', 'P', 'ARR');
$rvars = cot_import('rvars', 'P', 'ARR');


if (count($rfield) && !empty($c))
{
	foreach ($rid as $key => $val)
	{
		$menu['ex_field'] = cot_import($rfield[$key], 'D', 'TXT');
		$menu['ex_cat'] = $c;
		$menu['ex_desc'] = cot_import($rdesc[$key], 'D', 'TXT');
		$menu['ex_num'] = cot_import($rnum[$key], 'D', 'TXT');
		
		$menu['ex_type'] = cot_import($rtype[$key], 'D', 'TXT');
		$menu['ex_filter'] = cot_import($rfilter[$key], 'D', 'BOL') ? 1 : 0;
		$menu['ex_vars'] = cot_import($rvars[$key], 'D', 'TXT');
			
		if ($val == 'new' && (!empty($menu['ex_field']) || !empty($menu['ex_desc'])))
		{
			$db->insert($db_exflgroupeditor_filter, $menu);
		}
		else
		{
			if(!empty($menu['ex_field']) || !empty($menu['ex_desc']))
			{
				$db->update($db_exflgroupeditor_filter, $menu, "ex_id='".(int)$val."'");
			}
			else
			{
				$db->delete($db_exflgroupeditor_filter, "ex_id='".(int)$val."'");
			}
		}
	}
	$cache && $cache->db->remove('exfldcat_list_filter', 'system');

}

$cache && $cache->db->remove('exfldcat_list_filter', 'system');

$sskin = cot_tplfile('exfldgroupeditor.tools.filter', 'plug');
$tt = new XTemplate($sskin);

	$tt->assign(array(
		'EXFLD_CAT' => cot_selectbox_structure('page', $c, 'c'),
		'EXFLD_CATACTION' => cot_url('admin', 'm=other&p=exfldgroupeditor&l=filter&l=filter'),
	));
$filter_type = array(
	'is' => $L['select_filter_is'],
	'more' => $L['select_filter_more'],
	'less' => $L['select_filter_less'],
	'more-less' => $L['select_filter_more-less'],
	'short' => $L['select_filter_short'],
	'shortmore' => $L['select_filter_shortmore'],
	'shortless' => $L['select_filter_shortless'],
	'shortmore-less' => $L['select_filter_shortmore-less'],
	'isset' => $L['select_filter_isset'],
	'like' => $L['select_filter_like'],
	'check' => $L['select_filter_check'],
	'select' => $L['select_filter_select'],
	'multi' => $L['select_filter_multi'],
	'radio' => $L['select_filter_radio'],
	'multiadd' => $L['select_filter_multiadd']);

$sql_count = $db->query("SELECT ex_cat, COUNT(*) as ex_count FROM $db_exflgroupeditor_filter WHERE 1 GROUP BY ex_cat");
foreach ($sql_count->fetchAll() as $rowC)
{
	$tt->assign(array(
		'EXFLD_CAT_NAME' => $structure['page'][$rowC['ex_cat']]['title'],
		'EXFLD_CAT_URL' => cot_url('admin', 'm=other&p=exfldgroupeditor&l=filter&c='.$rowC['ex_cat']),
	));	
	$tt->parse('MAIN.CATEXISTS');
}
	
if(!empty($c))
{
	$res = $db->query("SELECT * FROM $db_extra_fields WHERE field_location = '".$db_pages."' ORDER BY field_name ASC");
	$exfld = array();
	foreach ($res->fetchAll() as $row)
	{
		$desc = (!empty($row['field_description'])) ? $row['field_name'] . ": " . $row['field_description'] : $row['field_name'];
		$exfld[$row['field_name']] = $desc;
	}
	
	$sql = $db->query("SELECT * FROM $db_exflgroupeditor_filter WHERE ex_cat = '" . $db->prep($c) . "' ORDER BY ex_num ASC");
	$i = 0;
	while ($row = $sql->fetch())
	{
		$i++;
		$qid = $row['ex_id'];
		$tt->assign(array(
			'EXFLD_NUM' => cot_inputbox('hidden', 'rid['.$i.']', $row['ex_id'], 'size="4"  class="rid"')
				.cot_inputbox('text', 'rnum['.$i.']', $row['ex_num'], 'class="rnum"'),
			'EXFLD_EXFLD' => cot_selectbox($row['ex_field'], 'rfield['.$i.']', array_keys($exfld), array_values($exfld), true, 'class="rfield"'),
			'EXFLD_DESC' => cot_inputbox('text', 'rdesc['.$i.']', $row['ex_desc'], 'size="16" class="rdesc"'),
			'EXFLD_TYPE' => cot_selectbox($row['ex_type'], 'rtype['.$i.']', array_keys($filter_type), array_values($filter_type), true, 'class="rtype"'),
			'EXFLD_VARS' => cot_inputbox('text', 'rvars['.$i.']', $row['ex_vars'], 'size="16" class="rvars"'),
			'EXFLD_FILTER' => cot_checkbox($row['ex_filter'], 'rfilter['.$i.']', '', 'title="'.$L['ex_Any'].'"'),
			'EXFLD_ID' => $qid,
		));
		
		$tt->parse('MAIN.EDIT.ROW');
	}
	
	$tt->assign(array(
		'EXFLD_NUM' => cot_inputbox('hidden', 'rid[]', 'new', 'size="4"  class="rid"')
			.cot_inputbox('text', 'rnum[]', '', 'class="rnum"'),
		'EXFLD_EXFLD' => cot_selectbox('', 'rfield[]', array_keys($exfld), array_values($exfld), true, 'class="rfield"'),
		'EXFLD_DESC' => cot_inputbox('text', 'rdesc[]', '', 'size="16" class="rdesc"'),
		'EXFLD_TYPE' => cot_selectbox('', 'rtype[]', array_keys($filter_type), array_values($filter_type), true, 'class="rtype"'),
		'EXFLD_VARS' => cot_inputbox('text', 'rvars[]', $row['ex_vars'], 'size="16" class="rvars"'),
		'EXFLD_FILTER' => cot_checkbox($row['ex_filter'], 'rfilter[]', '', 'title="'.$L['ex_Any'].'"'),
		'EXFLD_ID' => 'new',
	));
	$tt->parse('MAIN.EDIT.ROW');
	$tt->assign(array(
		'EXFLD_ACTION' => cot_url('admin', 'm=other&p=exfldgroupeditor&l=filter&c='.$c),
	));	
	$tt->parse('MAIN.EDIT');
}

$tt->parse('MAIN');
$plugin_body =$tt->text('MAIN');

