<?php

/**
 * plugin Exfld Group Editor for Cotonti Siena
 * 
 * @package Exfld Group Editor
 * @version 1.0.0
 * @author esclkm
 * @copyright esclkm
 * @license BSD
 *  */
// Generated by Cotonti developer tool (littledev.ru)
defined('COT_CODE') or die('Wrong URL.');
global $db_exflgroupeditor, $db_exflgroupeditor_filter, $db_x, $exfldcat_list, $exfldcat_list_filter;
$db_exflgroupeditor = (isset($db_exflgroupeditor)) ? $db_exflgroupeditor : $db_x.'exflgroupeditor';
$db_exflgroupeditor_filter = (isset($db_exflgroupeditor_filter)) ? $db_exflgroupeditor_filter : $db_x.'exflgroupeditor_filter';
function cot_exfld_get ()
{
	global $db, $db_exflgroupeditor;

	$sql = $db->query("SELECT * FROM $db_exflgroupeditor ORDER BY ex_cat ASC, ex_num ASC");
	$exfldcat = array();
	while ($row = $sql->fetch())
	{
		$exfldcat[$row['ex_cat']][$row['ex_id']] = $row;
	}
	return $exfldcat;
}
function cot_exfld_get_filter ()
{
	global $db, $db_exflgroupeditor_filter;

	$sql = $db->query("SELECT * FROM $db_exflgroupeditor_filter ORDER BY ex_cat ASC, ex_num ASC");
	$exfldcat = array();
	while ($row = $sql->fetch())
	{
		$exfldcat[$row['ex_cat']][$row['ex_id']] = $row;
	}
	return $exfldcat;
}
function cot_exfld_cat_get ($cat, $type = 'edit')
{
	global $structure, $exfldcat_list, $exfldcat_list_filter;
	
	$list = ($type == 'filter') ? $exfldcat_list_filter : $exfldcat_list;

	if (!isset($structure['page'][$cat]))
	{
		return array();
	}
	if (isset($list[$cat]))
	{
		return $list[$cat];
	}
	else
	{
		$struct = cot_structure_parents('page', $cat);
		$struct = array_reverse($struct);
		foreach ($struct as $str)
		{
			if (isset($list[$str]))
			{
				return $list[$str];
			}
		}
		
	}
	return array();
}

if (!isset($exfldcat_list))
{
				
	$exfldcat_list = cot_exfld_get();
	
}

if (!isset($exfldcat_list_filter))
{
				
	$exfldcat_list_filter = cot_exfld_get_filter();
	
}