<?php

/** 
 * [BEGIN_COT_EXT]
 * Hooks=pageplus.tags
 * [END_COT_EXT]
 */
 
/**
 * plugin Page Plus Cat Info for Cotonti Siena
 * 
 * @package pagepluscatinfo
 * @version 1.0.0
 * @author esclkm
 * @copyright 
 * @license BSD
 *  */
// Generated by Cotonti developer tool (littledev.ru)
defined('COT_CODE') or die('Wrong URL.');
global $db, $db_structure, $L;
if(!empty($cat))
{
	$catd_res = $db->query("SELECT structure_text, structure_text_after, structure_desc, structure_title 
		FROM $db_structure WHERE structure_code = '$cat' AND structure_area='page'");

	if ($catd = $catd_res->fetch())
	{
		$t->assign(array(
			'LIST_TITLE' => $catd['structure_title'],
			'LIST_DESC' => $catd['structure_desc'],
			'LIST_TEXT' => cot_parse($catd['structure_text'], true),
			'LIST_TEXT_AFTER' => cot_parse($catd['structure_text_after'], true),
			'LIST_TEXTEDIT' => cot_auth('page', $cat, 'A') ? '<a href="'.cot_url('plug', 'e=catdesc&c='.$cat).'">'.$L['catdesc_edit'].'</a>' : '',
			'LIST_TEXTEDIT_URL' => cot_auth('page', $cat, 'A') ? cot_url('plug', 'e=catdesc&c='.$cat) : '',
			'LIST_ADD_URL' => cot_auth('page', $cat, 'A') ? cot_url('page', 'm=add&c='.$cat) : '',
		));
	}
}

?>