<?php


/**
 * [BEGIN_COT_EXT]
 * Code=pagepluscatinfo
 * Name=Page Plus Cat Info
 * Category=misc-ext
 * Description=
 * Version=1.0.0
 * Date=2015-12-05
 * Author=esclkm
 * Auth_guests=R
 * Lock_guests=12345A
 * Auth_members=RW
 * [END_COT_EXT]
 * 
 *  */

/**
 * plugin Page Plus Cat Info for Cotonti Siena
 * 
 * @package pagepluscatinfo
 * @version 1.0.0
 * @author esclkm
 * @copyright 
 * @license BSD
 *  */
// Generated by Cotonti developer tool (littledev.ru)
defined('COT_CODE') or die('Wrong URL');

?>