<?php
/**
 * plugin Config Editor for Cotonti Siena
 * 
 * @package configeditor
 * @version 1.0.0
 * @author esclkm
 * @copyright 
 * @license BSD
 *  */
// Generated by Cotonti developer tool (littledev.ru)
defined('COT_CODE') or die('Wrong URL');

$L['info_desc'] = 'Plugin Info';

$L['Custom_configs'] = "Пользовательские настройки";
$L['edit_cats'] = "Редактирование категорий";
$L['edit_cat'] = "Редактирование опций";
$L['add_cat'] = "Добавить категорию";
$L['err_no_name'] = "Код не может быть пустым";
$L['err_exists_name'] = "Данный код уже существует";
$L['added_success'] = "Успешно добавлено";
$L['updated_success'] = "Успешно обновлено";
$L['deleted_success'] = "Запись удалена";

$L['ccfg_type_text'] = 'Текстовое поле';
$L['ccfg_type_string'] = 'Поле ввода';
$L['ccfg_type_select'] = 'Селект';
$L['ccfg_type_callback'] = 'Callback';
$L['ccfg_type_hidden'] = 'Скрытое';
$L['ccfg_type_radio'] = 'Радио Выкл / Вкл';
$L['ccfg_type_separator'] = 'Разделитель';
$L['ccfg_type_range'] = 'Диапазон';
$L['ccfg_type_custom'] = 'Пользовательский тип';

$L['ccfg_variants'] = 'Варианты значений';
