<?php

/** 
 * [BEGIN_COT_EXT]
 * Hooks=pagetags.main
 * [END_COT_EXT]
 */
 
/**
 * plugin landingextrapage for Cotonti Siena
 * 
 * @package landingextrapage
 * @version 1.0.0
 * @author esclkm
 * @copyright 
 * @license BSD
 *  */
// Generated by Cotonti developer tool (littledev.ru)
defined('COT_CODE') or die('Wrong URL.');
require_once cot_incfile('landingextrapage', 'plug');
require_once cot_langfile('landingextrapage', 'plug');


$lep = new landingextrapage($pag['page_landingextrapage']);

$temp_array['LANDINGINDEXPAGE'] = $lep->output();
 

?>
 
