<?php

/** 
 * [BEGIN_COT_EXT]
 * Hooks=page.add.add.first, page.edit.update.first
 * [END_COT_EXT]
 */
 
/**
 * plugin landingextrapage for Cotonti Siena
 * 
 * @package landingextrapage
 * @version 1.0.0
 * @author esclkm
 * @copyright 
 * @license BSD
 *  */
// Generated by Cotonti developer tool (littledev.ru)
defined('COT_CODE') or die('Wrong URL.');

require_once cot_langfile('landingextrapage', 'plug');
require_once cot_incfile('landingextrapage', 'plug');
$lep = new landingextrapage();
$lep->update();

$_POST['npagelandingextrapage'] = $lep->save();

?>
 
