<?php
/**
 * plugin Custom Configs for Cotonti Siena
 * 
 * @package customconfigs
 * @version 1.0.0
 * @author esclkm
 * @copyright 
 * @license BSD
 *  */
// Generated by Cotonti developer tool (littledev.ru)
defined('COT_CODE') or die('Wrong URL');

$L['info_desc'] = 'Plugin Info';

$L['Custom_configs'] = "Пользовательские настройки";
$L['edit_cats'] = "Редактирование категорий";
$L['edit_cat'] = "Редактирование опций";
$L['add_cat'] = "Добавить категорию";
$L['err_no_name'] = "Название не может быть пустым";
$L['ccfg_type_text'] = 'Текстовое поле';
$L['ccfg_type_string'] = 'Поле ввода';
$L['ccfg_type_select'] = 'Селект';
$L['ccfg_type_radio'] = 'Радио Выкл / Вкл';
$L['ccfg_type_separator'] = 'Разделитель';
$L['ccfg_type_range'] = 'Диапазон';

$L['ccfg_variants'] = 'Варианты значений';
