<?php

/** 
 * [BEGIN_COT_EXT]
 * Hooks=tools
 * [END_COT_EXT]
 */
 
/**
 * plugin Exfld Group Editor for Cotonti Siena
 * 
 * @package Exfld Group Editor
 * @version 1.0.0
 * @author esclkm
 * @copyright esclkm
 * @license BSD
 *  */
// Generated by Cotonti developer tool (littledev.ru)
defined('COT_CODE') or die('Wrong URL.');

require_once cot_langfile('exfldgroupeditor', 'plug');
require_once cot_incfile('exfldgroupeditor', 'plug');
require_once cot_incfile('page', 'module');
require_once cot_incfile('forms');

$t = new XTemplate(cot_tplfile('exfldgroupeditor', 'plug'));

$c = cot_import('c', 'G', 'TXT');
$l = cot_import('l', 'G', 'TXT');

if ($l != 'filter')
{
	$l = 'edit';
}

require_once cot_incfile('exfldgroupeditor', 'plug', 'tools.'.$l);



