<?php


/**
 * [BEGIN_COT_EXT]
 * Code=exfldgroupeditor
 * Name=Exfld Group Editor
 * Category=development-maintenance
 * Description=Exfld Group Editor
 * Version=1.0.0
 * Date=2014-04-12
 * Author=esclkm
 * Copyright=esclkm
 * Auth_guests=R
 * Lock_guests=12345A
 * Auth_members=RW
 * Requires_modules=page
 * [END_COT_EXT]
 * 
 *  */

/**
 * plugin Exfld Group Editor for Cotonti Siena
 * 
 * @package Exfld Group Editor
 * @version 1.0.0
 * @author esclkm
 * @copyright esclkm
 * @license BSD
 *  */
// Generated by Cotonti developer tool (littledev.ru)
defined('COT_CODE') or die('Wrong URL');

?>