<?php

/** 
 * [BEGIN_COT_EXT]
 * Hooks=global
 * [END_COT_EXT]
 */
 
/**
 * plugin Custom Configs for Cotonti Siena
 * 
 * @package customconfigs
 * @version 1.0.0
 * @author esclkm
 * @copyright 
 * @license BSD
 *  */
// Generated by Cotonti developer tool (littledev.ru)
defined('COT_CODE') or die('Wrong URL.');

require_once cot_incfile('customconfigs', 'plug');

ccfg::load();