<?php


/**
 * [BEGIN_COT_EXT]
 * Code=customconfigs
 * Name=Custom Configs
 * Category=misc-ext
 * Description=Admin tool for creating and modifying custom configs
 * Version=1.0.0
 * Date=2015-05-18
 * Author=esclkm
 * Auth_guests=R
 * Lock_guests=12345A
 * Auth_members=RW
 * [END_COT_EXT]
 * 
 *  */

/**
 * plugin Custom Configs for Cotonti Siena
 * 
 * @package customconfigs
 * @version 1.0.0
 * @author esclkm
 * @copyright 
 * @license BSD
 *  */
// Generated by Cotonti developer tool (littledev.ru)
defined('COT_CODE') or die('Wrong URL');

?>