<?php

/**
 * [BEGIN_COT_EXT]
 * Hooks=page.list.main
 * [END_COT_EXT]
 */
/**
 * plugin pagelisteditor for Cotonti Siena
 * 
 * @package pagelisteditor
 * @version 1.0.0
 * @author esclkm
 * @copyright 
 * @license BSD
 *  */
// Generated by Cotonti developer tool (littledev.ru)
defined('COT_CODE') or die('Wrong URL.');

$action = cot_import('action', 'G', 'TXT');

//$mskin = cot_tplfile(array('page', 'list', 'edit', $cat['tpl']));
if ($action == 'edit')
{
	$mskin = cot_tplfile(array('page', 'list', 'edit', $cat['tpl']));
}