<?php

/**
 * plugin Config Editor for Cotonti Siena
 * 
 * @package configeditor
 * @version 1.0.0
 * @author esclkm
 * @copyright 
 * @license BSD
 *  */
// Generated by Cotonti developer tool (littledev.ru)
defined('COT_CODE') or die('Wrong URL.');
/* @var $db CotDB */
/* @var $cache Cache */
/* @var $t Xtemplate */

//$adminpath[] = array(cot_url('admin', array('m' => 'other', 'p' => 'configeditor')), $L['Custom_configs']);
$adminpath[] = $L['edit_cats'];

if($a == 'add')
{
	$name = cot_import('rname', 'P', "ALP");
	$title = cot_import('rtitle', 'P', "TXT");
	$desc = cot_import('rdesc', 'P', "HTM");
	if(empty($name))
	{
		cot_error($L['err_no_name']);
	}
	if(in_array($name, cfg_editor::cat_exists_list()))
	{
		cot_error($L['err_exists_name']);
	}	
	if(!cot_error_found())
	{
		cfg_editor::cat_add($name, $title, $desc);
		cot_message('added_success');
	}
	cot_redirect(cot_url('admin', array('m' => 'other', 'p' => 'configeditor', 'n' => 'editcat'), '', true));
}
if($a == 'update')
{

	$titles = cot_import('rtitle', 'P', "ARR");
	$descs = cot_import('rdesc', 'P', "ARR");
	$names = array_keys($titles);
	foreach($names as $name)
	{
			$name = cot_import($name, 'D', "ALP");
			$title = cot_import($titles[$name], 'D', "TXT");
			$desc = cot_import($descs[$name], 'D', "HTM");

			cfg_editor::cat_edit($name, $title, $desc);
			
	}
	cot_message('updated_success');
	cot_redirect(cot_url('admin', array('m' => 'other', 'p' => 'configeditor', 'n' => 'editcat'), '', true));
}
if($a == 'delete')
{
	cot_check_xg();
	$name = cot_import('rname', 'G', "ALP");
	cfg_editor::cat_delete($name);
	cot_message('deleted_success');
	cot_redirect(cot_url('admin', array('m' => 'other', 'p' => 'configeditor', 'n' => 'editcat'), '', true));
}
$system_cats = cfg_editor::cat_system_list();
foreach ($system_cats as $cat)
{
	$t->assign(array(	
		'FORM_EDIT_TITLE' => cot_inputbox('text', '_rtitle['.$cat.']', $L['core_'.$cat], array('maxlength' => '255', 'readonly'=>'readonly')),
		'FORM_EDIT_DESC' => cot_textarea('_rdesc['.$cat.']',  $L['core_'.$cat.'_desc'], 1, 60, array('maxlength' => '255', 'readonly'=>'readonly')),
		'FORM_EDIT_NAME' => $cat,
		'FORM_EDIT_HREF' => cot_url('admin', array('m' => 'other', 'p' => 'configeditor', 'n' => 'edit', 'c' => $cat)),
		'FORM_EDIT_CONFIG_HREF' => cot_url('admin', array('m' => 'config', 'n'=> 'edit', 'o' => 'core', 'p' => $cat)),
		'FORM_EDIT_DELETE_URL' => '',
	));
	$t->parse('MAIN.ROW');
}
$rows = cfg_editor::cat_list();
foreach ($rows as $row)
{
	$t->assign(array(	
		'FORM_EDIT_TITLE' => cot_inputbox('text', 'rtitle['.$row['configcat_name'].']', $row['configcat_title'], array('maxlength' => '255')),
		'FORM_EDIT_DESC' => cot_textarea('rdesc['.$row['configcat_name'].']',  $row['configcat_desc'], 1, 60),		
		'FORM_EDIT_NAME' => $row['configcat_name'],
		'FORM_EDIT_HREF' => cot_url('admin', array('m' => 'other', 'p' => 'configeditor', 'n' => 'edit', 'c' => $row['configcat_name'])),
		'FORM_CONFIG_HREF' => cot_url('admin', array('m' => 'config', 'n'=> 'edit', 'o' => 'core', 'p' => $row['configcat_name'])),
		'FORM_EDIT_DELETE_URL' => cot_url('admin', array('m' => 'other', 'p' => 'configeditor', 'n' => 'editcat', 'a' => 'delete', 'rname' => $row['configcat_name'],'x' => $sys['xk'])),
	));
	$t->parse('MAIN.ROW');
}
if(!count($rows) && !count($system_cats))
{
	$t->parse('MAIN.NOROW');
}
$t->assign(array(
	'FORM_EDIT_URL' => cot_url('admin', array('m' => 'other', 'p' => 'configeditor', 'n' => 'editcat', 'a' => 'update')),
	'FORM_ADD_URL' => cot_url('admin', array('m' => 'other', 'p' => 'configeditor', 'n' => 'editcat', 'a' => 'add')),
	'FORM_ADD_TITLE' => cot_inputbox('text', 'rtitle', '', array('maxlength' => '255')),
	'FORM_ADD_NAME' => cot_inputbox('text', 'rname', '', array('size' => '20', 'maxlength' => '32')),
	'FORM_ADD_DESC' => cot_textarea('rdesc', '', 1, 60),
));
cot_display_messages($t);