<?php


/**
 * [BEGIN_COT_EXT]
 * Code=randlist
 * Name=randlist
 * Category=misc-ext
 * Description=randlist
 * Version=1.0.0
 * Date=2015-11-17
 * Author=esclkm
 * Auth_guests=R
 * Lock_guests=12345A
 * Auth_members=RW
 * [END_COT_EXT]
 * 
 *  */

/**
 * plugin randlist for Cotonti Siena
 * 
 * @package randlist
 * @version 1.0.0
 * @author esclkm
 * @copyright 
 * @license BSD
 *  */
// Generated by Cotonti developer tool (littledev.ru)
defined('COT_CODE') or die('Wrong URL');

?>