<?php

/** 
 * [BEGIN_COT_EXT]
 * Hooks=admin.config.first
 * [END_COT_EXT]
 */
 
/**
 * plugin Config Editor for Cotonti Siena
 * 
 * @package configeditor
 * @version 1.0.0
 * @author esclkm
 * @copyright 
 * @license BSD
 *  */
// Generated by Cotonti developer tool (littledev.ru)
defined('COT_CODE') or die('Wrong URL.');
/* @var $db CotDB */
/* @var $cache Cache */
/* @var $t Xtemplate */
require_once cot_incfile('configeditor', 'plug');

$sql = $db->query("SELECT * FROM $db_configeditor");
while($row = $sql->fetch())
{
	$name = $row['configcat_name'];
	$L['core_'.$name] = $row['configcat_title'];
	$L['core_'.$name.'_desc'] = $row['configcat_desc'];
}

$sql = $db->query("SELECT * FROM $db_config  WHERE config_owner = 'core' AND config_donor='configeditor'");
while($row = $sql->fetch())
{
	$name = $row['config_name'];
	$L['cfg_'.$name] = $row['config_text'];
	$L['cfg_'.$name.'_hint'] = $row['config_desc'];
}