<?php

/** 
 * [BEGIN_COT_EXT]
 * Hooks=tools
 * [END_COT_EXT]
 */
 
/**
 * plugin Config Editor for Cotonti Siena
 * 
 * @package configeditor
 * @version 1.0.0
 * @author esclkm
 * @copyright 
 * @license BSD
 *  */
// Generated by Cotonti developer tool (littledev.ru)
defined('COT_CODE') or die('Wrong URL.');

require_once cot_incfile('configeditor', 'plug');

if (!in_array($n, array('edit')))
{
	$n = 'editcat';
}

if (file_exists(cot_incfile('configeditor', 'plug', 'admin.'.$n)))
{
	$t = new XTemplate(cot_tplfile('configeditor.admin.'.$n, 'plug'));
	require_once cot_incfile('configeditor', 'plug', 'admin.'.$n);
	$t->parse('MAIN');
	$adminmain = $t->text('MAIN');
}
else
{
	// Error page
	cot_die_message(404);
	exit;
}
