<?php

/**
 * plugin Custom Configs for Cotonti Siena
 * 
 * @package customconfigs
 * @version 1.0.0
 * @author esclkm
 * @copyright 
 * @license BSD
 *  */
// Generated by Cotonti developer tool (littledev.ru)
defined('COT_CODE') or die('Wrong URL.');
/* @var $db CotDB */
/* @var $cache Cache */
/* @var $t Xtemplate */
$c = cot_import('c', 'G', 'ALP');
if(!$c)
{
	cot_redirect(cot_url('admin', array('m' => 'other', 'p' => 'customconfigs'), '', true));
}
$info = ccfg::cat_info($c);
if(!$info)
{
	cot_redirect(cot_url('admin', array('m' => 'other', 'p' => 'customconfigs'), '', true));
}
if($a == 'update')
{
	$rows = ccfg::config_list($c);
	//cot_print($rows, $_POST);
	foreach ($rows as $row)
	{
		if(isset($_POST['rccfg_'.$row['config_name']]))
		{
			$val = cot_import('rccfg_'.$row['config_name'], 'P', 'NOC');
			ccfg::config_change($c, $row['config_name'], $val);
		}
	}
	$cache && $cache->clear();
	cot_redirect(cot_url('admin', array('m' => 'other', 'p' => 'customconfigs', 'n' => 'set', 'c' => $c), '', true));
}
if($a == 'default')
{
	cot_check_xg();
	$name = cot_import('rname', 'G', "ALP");
	ccfg::config_setdefault($c, $name);
	$cache && $cache->clear();
	cot_redirect(cot_url('admin', array('m' => 'other', 'p' => 'customconfigs', 'n' => 'set', 'c' => $c), '', true));
}

$adminpath[] = $info['configcat_title'];
$rows = ccfg::config_list($c);
foreach ($rows as $row)
{
	$t->assign(array(
		'FORM_UPDATE_NAME' => $row['config_name'],
		'FORM_UPDATE_TAG' => "{PHP.custom_cfg.".$c.".".$row['config_name']."}",
		'FORM_UPDATE_TITLE' => $row['config_title'],
		'FORM_UPDATE_DESC' => cot_parse($row['config_desc']),
		'FORM_UPDATE_SEPARATOR' => $row['config_type'] == COT_CUSTOM_CONFIG_TYPE_SEPARATOR,
		'FORM_UPDATE_INPUT' => ccfg::config_input('rccfg_'.$row['config_name'], $row['config_type'], $row['config_value'], $row['config_variants']),
		'FORM_UPDATE_TYPE' => $row['config_type'],
		'FORM_UPDATE_DEFAULT_URL' => cot_url('admin', array('m' => 'other', 'p' => 'customconfigs', 'n' => 'set', 'c' => $c, 'a' => 'default', 'rname' => $row['config_name'],'x' => $sys['xk'])),
	));
	$t->parse('MAIN.ROW');
}
if(!count($rows))
{
	$t->parse('MAIN.NOROW');
}
$t->assign(array(
	'FORM_UPDATE_URL' => cot_url('admin', array('m' => 'other', 'p' => 'customconfigs', 'n' => 'set', 'a' => 'update', 'c' => $c)),
	'CAT_TITLE' => $info['configcat_title'],
	'CAT_DESC' => cot_parse($info['configcat_desc']),
	'EDITHREF' => cot_url('admin', array('m' => 'other', 'p' => 'customconfigs', 'n' => 'edit', 'c' => $c)),
));
cot_display_messages($t);