<?php
/**
 * plugin Exfld Group Editor for Cotonti Siena
 * 
 * @package Exfld Group Editor
 * @version 1.0.0
 * @author esclkm
 * @copyright esclkm
 * @license BSD
 *  */
// Generated by Cotonti developer tool (littledev.ru)
defined('COT_CODE') or die('Wrong URL');

$L['info_desc'] = 'Plugin Info';

$L['Select_cat'] = 'Выберите категорию';

$L['ex_Add'] = 'Отображать при создании страницы';
$L['ex_Edit'] = 'Отображать при правке страницы';
$L['ex_List'] = 'Отображать в списках';
$L['ex_Page'] = 'Отображать в страницах';
$L['ex_Any'] = 'Отображать при произвольном выводе страницы';
$L['ex_Filter'] = 'Отображать в списке сортировки';
$L['ex_vars'] = 'Значения';

$L['cfg_select'] = array('select', 'select desc');
$L['cfg_select_params'] = array('one', 'two', 'three');
$L['cfg_radio'] = array('radio', 'radio desc');
$L['cfg_separatortext'] = 'separator text';
$L['cfg_range'] = array('range', 'range desc');
$L['cfg_textarea'] = array('textarea', 'textarea desc');



$L['select_filter_is'] = 'равно';
$L['select_filter_more'] = 'больше';
$L['select_filter_less'] = 'меньше';
$L['select_filter_more-less'] = 'больше-меньше';
$L['select_filter_short'] = 'краткий равно';
$L['select_filter_shortmore'] = 'краткий больше';
$L['select_filter_shortless'] = 'краткий меньше';
$L['select_filter_shortmore-less'] = 'краткий больше-меньше';
$L['select_filter_isset'] = 'есть значение';
$L['select_filter_like'] = 'подобно';
$L['select_filter_check'] = 'галочка';
$L['select_filter_select'] = 'селект';
$L['select_filter_multi'] = 'мультивыбор';
$L['select_filter_radio'] = 'радиовыбор';
$L['select_filter_multiadd'] = 'мультивыбор, 2 вариант';

?>