<?php


/**
 * [BEGIN_COT_EXT]
 * Code=bootstrap
 * Name=Bootstrap 3 Compliller
 * Category=misc-ext
 * Description=compiles Bootstrap  *.less files
 * Version=1.0.0
 * Date=2014-09-12
 * Author=esclkm
 * Auth_guests=R
 * Lock_guests=12345A
 * Auth_members=RW
 * [END_COT_EXT]
 * 
 *  */

/**
 * plugin Bootstrap 3 Compliller for Cotonti Siena
 * 
 * @package bootstrap
 * @version 1.0.0
 * @author esclkm
 * @copyright 
 * @license BSD
 *  */
// Generated by Cotonti developer tool (littledev.ru)
defined('COT_CODE') or die('Wrong URL');

?>