<?php

/** 
 * [BEGIN_COT_EXT]
 * Hooks=input
 * [END_COT_EXT]
 */
 
/**
 * plugin Bootstrap 3 Compliller for Cotonti Siena
 * 
 * @package bootstrap
 * @version 1.0.0
 * @author esclkm
 * @copyright 
 * @license BSD
 *  */
// Generated by Cotonti developer tool (littledev.ru)
defined('COT_CODE') or die('Wrong URL.');

require_once $cfg['plugins_dir']."/bootstrap/lessphp/Less.php";
//cot_print('111');
function compile_botstrap_less ($theme, $input, $output='', $compress =false)
{
	global $cfg;
	$output = empty($output) ? $input : $output;
	$output = $cfg['themes_dir'].'/'.$theme.'/css/'.$output.'.css';
	$input = $cfg['themes_dir'].'/'.$theme.'/less/'.$input.'.less';
//	cot_print($output,$input);
	if (file_exists($output) && file_exists($input))
	{
		$filetimecss = filemtime($output);
		$filetimeless = filemtime($input);
	//	cot_print('css', cot_date('datetime_full', $filetimecss), 'less', cot_date('datetime_full', $filetimeless), cot_date('datetime_full'), $filetimecss > $filetimeless);
		if($filetimecss > $filetimeless)
		{
			return false;
		}
		else
		{
			unlink($output);
		//	cot_print("deleted");
		}
	}

	$options = array('relativeUrls' => false);
	if($compress)
	{
		$options['compress'] = true;
	}
	
	$parser = new Less_Parser($options);
	$parser->SetImportDirs(array($cfg['themes_dir'].'/'.$theme.'/less' => $cfg['themes_dir'].'/'.$theme.'/less',
		$cfg['plugins_dir']."/bootstrap/bootstrap/less" => $cfg['plugins_dir']."/bootstrap/bootstrap/less"));
	
	$parser->parseFile($input);
	$css = $parser->getCss();
	
	if(!file_exists ($cfg['themes_dir'].'/'.$theme.'/css'))
	{
		mkdir($cfg['themes_dir'].'/'.$theme.'/css');
	}
	
	file_put_contents($output, $css);
	return true;
}