<?php

/** 
 * [BEGIN_COT_EXT]
 * Hooks=page.edit.update.error
 * Order=1000
 * [END_COT_EXT]
 */
 
/**
 * plugin Page Edied Redirect To Index for Cotonti Siena
 * 
 * @package pageaddtoind
 * @version 1.0.0
 * @author esclkm
 * @copyright 
 * @license BSD
 *  */
// Generated by Cotonti developer tool (littledev.ru)
defined('COT_CODE') or die('Wrong URL.');

if (!cot_error_found())
{
	cot_page_update($id, $rpage);

	switch ($rpage['page_state'])
	{
		case 0:
			$r_url = cot_url('index', '', '', true);
			break;
		case 1:
			$r_url = cot_url('message', 'msg=300', '', true);
			break;
		case 2:
			cot_message($L['page_savedasdraft']);
			$r_url = cot_url('page', 'm=edit&id=' . $id, '', true);
			break;
	}
	cot_redirect($r_url);
}
else
{
	cot_redirect(cot_url('page', "m=edit&id=$id", '', true));
}