<?php


/**
 * [BEGIN_COT_EXT]
 * Code=pageaddtoind
 * Name=Page Edied Redirect To Index
 * Category=misc-ext
 * Description=pageaddtoind
 * Version=1.0.0
 * Date=2015-12-08
 * Author=esclkm
 * Auth_guests=R
 * Lock_guests=12345A
 * Auth_members=RW
 * [END_COT_EXT]
 * 
 *  */

/**
 * plugin Page Edied Redirect To Index for Cotonti Siena
 * 
 * @package pageaddtoind
 * @version 1.0.0
 * @author esclkm
 * @copyright 
 * @license BSD
 *  */
// Generated by Cotonti developer tool (littledev.ru)
defined('COT_CODE') or die('Wrong URL');

?>